name: Update database types
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Set up supabase cli
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: 'Generate database typescript types'
        shell: bash
        env:
          SUPABASE_REF_ID: ${{ secrets.SUPABASE_REF_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          OUTPUT_PATH: 'src/utils/database.types.ts'
        run: |
          if [ ! -f supabase/config.toml ]; then
            supabase init && supabase start
          fi
          supabase login --api-key ${SUPABASE_ACCESS_TOKEN}
          supabase link --project-ref ${SUPABASE_REF_ID} --password ${DB_PASSWORD}
          supabase gen types typescript --project-id ${SUPABASE_REF_ID} > ${OUTPUT_PATH}
      - name: Check for file changes & commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'src/utils/database.types.ts'
          commit_message: Update database types
          commit_user_name: Supabot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Supabot <41898282+github-actions[bot]@users.noreply.github.com>
          branch: supabot/update-database-types
          create_branch: true
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ github.token }}
          source_branch: supabot/update-database-types
          destination_branch: 'main'
          pr_allow_empty: false
          pr_title: '[Supabot] Update database type definitions'
          pr_body: |
            - Auto-generated by [Supabot](https://github.com/lyqht/generate-supabase-db-types-github-action)
